version: '3.4'

services:
  front:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  back:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


