version: '3.4'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  redis:
    image: redis:alpine
    
  dapr-placement:
    image: "daprio/dapr:latest"    
    command: ["./placement", "-port", "50000", "-log-level", "debug"]
    ports:
      - "50000:50000"

  blazorapp.server:
    image: ${DOCKER_REGISTRY-}blazorappserver
    build:
      context: .
      dockerfile: BlazorApp/Server/Dockerfile
    ports:
      - "51000:50001"


  blazorapp.server-dapr:
    image: "daprio/daprd:latest"
    command: ["./daprd", "-app-id", "Front", "-app-port", "80","-components-path","/components", "-placement-host-address", "dapr-placement:50000"]
    restart: always
    depends_on:
      - blazorapp.server
    network_mode: "service:blazorapp.server"
    environment:
      DAPR_PLACEMENT_HOST: dapr-placement
    volumes:
      - "./dapr/components/:/components"    
